//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum Format {
  JPG,
  PNG,
  TIFF,
  WEBP,
  PVR,
  ETC,
  ETC2,
  S3TC,
  ATITC,
  TGA,
  RAW_DATA,
  UNKNOWN
}
