//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PackageWrap {
  public static Package PACKAGE_OPEN(string filename, ZSTDCompress comprer, bool readOnly) {
    global::System.IntPtr cPtr = PackageWrapPINVOKE.PACKAGE_OPEN(filename, ZSTDCompress.getCPtr(comprer), readOnly);
    Package ret = (cPtr == global::System.IntPtr.Zero) ? null : new Package(cPtr, false);
    if (PackageWrapPINVOKE.SWIGPendingException.Pending) throw PackageWrapPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
