//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TexInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TexInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TexInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TexInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TexInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PackageWrapPINVOKE.delete_TexInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public short offx {
    set {
      PackageWrapPINVOKE.TexInfo_offx_set(swigCPtr, value);
    } 
    get {
      short ret = PackageWrapPINVOKE.TexInfo_offx_get(swigCPtr);
      return ret;
    } 
  }

  public short offy {
    set {
      PackageWrapPINVOKE.TexInfo_offy_set(swigCPtr, value);
    } 
    get {
      short ret = PackageWrapPINVOKE.TexInfo_offy_get(swigCPtr);
      return ret;
    } 
  }

  public short wid {
    set {
      PackageWrapPINVOKE.TexInfo_wid_set(swigCPtr, value);
    } 
    get {
      short ret = PackageWrapPINVOKE.TexInfo_wid_get(swigCPtr);
      return ret;
    } 
  }

  public short hei {
    set {
      PackageWrapPINVOKE.TexInfo_hei_set(swigCPtr, value);
    } 
    get {
      short ret = PackageWrapPINVOKE.TexInfo_hei_get(swigCPtr);
      return ret;
    } 
  }

  public TexInfo() : this(PackageWrapPINVOKE.new_TexInfo(), true) {
  }

}
