//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum PKG_ERR {
  SUCCESS = 0,
  CODE_CHECKHEAD_FAIL = 1,
  FILE_NOT_FOUND_IN_PACKAGE,
  READ_HEAD_FAIL,
  PACKAGE_NOT_FOUND,
  OPEN_PACKAGE_FAIL,
  READ_PKG_INFO_FAIL,
  WRITE_FILE_FAIL,
  DECOMPRESS_FAIL,
  COMPRESS_FAIL,
  IS_REMOTE_FILE,
  INVALID_TEXTURE_DATA
}
