//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RemoteFileData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RemoteFileData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RemoteFileData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RemoteFileData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RemoteFileData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PackageWrapPINVOKE.delete_RemoteFileData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public global::System.IntPtr data {
    set {
      PackageWrapPINVOKE.RemoteFileData_data_set(swigCPtr, value);
    } 
    get {
      global::System.IntPtr ret = PackageWrapPINVOKE.RemoteFileData_data_get(swigCPtr);
      return ret;
    } 
  }

  public uint size {
    set {
      PackageWrapPINVOKE.RemoteFileData_size_set(swigCPtr, value);
    } 
    get {
      uint ret = PackageWrapPINVOKE.RemoteFileData_size_get(swigCPtr);
      return ret;
    } 
  }

  public uint compressedSize {
    set {
      PackageWrapPINVOKE.RemoteFileData_compressedSize_set(swigCPtr, value);
    } 
    get {
      uint ret = PackageWrapPINVOKE.RemoteFileData_compressedSize_get(swigCPtr);
      return ret;
    } 
  }

  public RemoteFileData() : this(PackageWrapPINVOKE.new_RemoteFileData(), true) {
  }

}
